### ISSUE TITLE
missing factory methods for `unsetSpecialRole` operation

### ISSUE THREAD

**Issue by EtienneWallet** [multiversx/mx-sdk-py#91]
# Description

The class `TokenManagementTransactionsFactory` defines the methods to execute the operation `setSpecialRole` for fungible, non fungible, semi fungible and meta tokens. However, it does not define the equivalent `unsetSpecialRole` operation.

# Action

If you are fine with it, I'll submit a PR for this operation (within two weeks maybe).
in this event, on which branch should I submit the PR? I don't see a develop branch or something equivalent.

**Comment by popenta** [comment]
Fixed in [this realease](https://github.com/multiversx/mx-sdk-py/releases/tag/v0.12.0).
